name: Build and Deploy to NuGet

on:
  push:
    branches:
      - main # or replace with the name of your default branch
    paths:
      - 'infrastructure/Common.Logging/src/Common.Logging/**' # adjust this to the path of your project's source code

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # adjust this to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore src/Common.Logging/Common.Logging.csproj

      - name: Build
        run: dotnet build src/Common.Logging/Common.Logging.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Common.Logging.Tests/Common.Logging.Tests.csproj --no-restore

      - name: Increment NuGet version
        uses: jenschude/nuget-version-action@v1.0.1
        with:
          path: src/Common.Logging/Common.Logging.csproj

      - name: Pack
        run: dotnet pack src/Common.Logging/Common.Logging.csproj --configuration Release --no-build --include-symbols --output out --include-source

      - name: Push to GitHub Packages
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/david-yaari/index.json
