# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.rabbitmq.name } }
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
