# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.kibana.name } }
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: kibana
          image: kibana:latest
          ports:
            - containerPort: 5601
