# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: { { .Values.kibana.name } }
spec:
  type: LoadBalancer
  ports:
    - port: 5601
  selector:
    app: { { .Values.kibana.name } }
