# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.elasticsearch.name } }
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:latest
          ports:
            - containerPort: 9200
