# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: { { .Values.elasticsearch.name } }
spec:
  type: LoadBalancer
  ports:
    - port: 9200
  selector:
    app: { { .Values.elasticsearch.name } }
