# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.seq.name } }
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: seq
          image: datalust/seq:latest
          ports:
            - containerPort: 80
            - containerPort: 5341
