apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-authentication
  template:
    metadata:
      labels:
        app: mongodb-authentication
    spec:
      containers:
        - name: mongodb-authentication
          image: mongo:latest
          resources:
            limits:
              cpu: '1'
              memory: '500Mi'
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
