apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.mongodb.deploymentName } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { .Values.mongodb.deploymentName } }
  template:
    metadata:
      labels:
        app: { { .Values.mongodb.deploymentName } }
    spec:
      containers:
        - name: { { .Values.mongodb.containerName } }
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: { { .Values.mongodb.volumeName } }
              mountPath: /data/db
      volumes:
        - name: { { .Values.mongodb.volumeName } }
          persistentVolumeClaim:
            claimName: { { .Values.mongodb.pvcName } }
