apiVersion: v1
kind: Service
metadata:
  name: { { .Values.mongodb.serviceName } }
spec:
  selector:
    app: { { .Values.mongodb.deploymentName } }
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
